### ISSUE TITLE
.dll not found

### ISSUE THREAD

**Issue by slowlearner2021** [AzAgarampur/byeintegrity4-uac#1]
Windows Build 19041

The code execution cannot proceed  MSVCP140D.dll not found.
The code execution cannot proceed  VCRUNTIME140D.dll not found.

Is it a error on my part? Thought i compiled correctly? Looked through the code, couldn't tell when you said "The code is pretty much self-explanatory, so I've only left a comment or two."  DO I NEED TO Undefine# SOME LINES?

**Comment by AzAgarampur** [comment]
These errors have nothing to do with the code; check your installation of the CRT.
